/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CommunityPost {
  'id' : bigint,
  'upvotes' : bigint,
  'resolved' : boolean,
  'title' : string,
  'description' : string,
  'category' : PostCategory,
  'location' : string,
}
export interface PlatformStats {
  'totalSchemes' : bigint,
  'totalUpvotes' : bigint,
  'totalPosts' : bigint,
  'totalStories' : bigint,
}
export type PostCategory = { 'womenEmpowerment' : null } |
  { 'education' : null } |
  { 'infrastructure' : null } |
  { 'agriculture' : null } |
  { 'digitalAccess' : null } |
  { 'health' : null };
export interface Scheme {
  'id' : bigint,
  'applyLink' : string,
  'name' : string,
  'eligibility' : string,
  'category' : SchemeCategory,
  'benefits' : string,
}
export type SchemeCategory = { 'finance' : null } |
  { 'education' : null } |
  { 'employment' : null } |
  { 'women' : null } |
  { 'agriculture' : null } |
  { 'health' : null };
export interface SuccessStory {
  'id' : bigint,
  'title' : string,
  'sdgTags' : Array<string>,
  'story' : string,
  'location' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addScheme' : ActorMethod<
    [string, SchemeCategory, string, string, string],
    bigint
  >,
  'addSuccessStory' : ActorMethod<
    [string, string, string, Array<string>],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllCommunityPosts' : ActorMethod<[], Array<CommunityPost>>,
  'getAllSchemes' : ActorMethod<[], Array<Scheme>>,
  'getAllSuccessStories' : ActorMethod<[], Array<SuccessStory>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPlatformStats' : ActorMethod<[], PlatformStats>,
  'getPostsByCategory' : ActorMethod<[PostCategory], Array<CommunityPost>>,
  'getSchemesByCategory' : ActorMethod<[SchemeCategory], Array<Scheme>>,
  'getTopUpvotedPosts' : ActorMethod<[bigint], Array<CommunityPost>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initialize' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markPostAsResolved' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitCommunityPost' : ActorMethod<
    [string, string, string, PostCategory],
    bigint
  >,
  'upvotePost' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];