/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SchemeCategory = IDL.Variant({
  'finance' : IDL.Null,
  'education' : IDL.Null,
  'employment' : IDL.Null,
  'women' : IDL.Null,
  'agriculture' : IDL.Null,
  'health' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PostCategory = IDL.Variant({
  'womenEmpowerment' : IDL.Null,
  'education' : IDL.Null,
  'infrastructure' : IDL.Null,
  'agriculture' : IDL.Null,
  'digitalAccess' : IDL.Null,
  'health' : IDL.Null,
});
export const CommunityPost = IDL.Record({
  'id' : IDL.Nat,
  'upvotes' : IDL.Nat,
  'resolved' : IDL.Bool,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'category' : PostCategory,
  'location' : IDL.Text,
});
export const Scheme = IDL.Record({
  'id' : IDL.Nat,
  'applyLink' : IDL.Text,
  'name' : IDL.Text,
  'eligibility' : IDL.Text,
  'category' : SchemeCategory,
  'benefits' : IDL.Text,
});
export const SuccessStory = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'sdgTags' : IDL.Vec(IDL.Text),
  'story' : IDL.Text,
  'location' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const PlatformStats = IDL.Record({
  'totalSchemes' : IDL.Nat,
  'totalUpvotes' : IDL.Nat,
  'totalPosts' : IDL.Nat,
  'totalStories' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addScheme' : IDL.Func(
      [IDL.Text, SchemeCategory, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addSuccessStory' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllCommunityPosts' : IDL.Func([], [IDL.Vec(CommunityPost)], ['query']),
  'getAllSchemes' : IDL.Func([], [IDL.Vec(Scheme)], ['query']),
  'getAllSuccessStories' : IDL.Func([], [IDL.Vec(SuccessStory)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPlatformStats' : IDL.Func([], [PlatformStats], ['query']),
  'getPostsByCategory' : IDL.Func(
      [PostCategory],
      [IDL.Vec(CommunityPost)],
      ['query'],
    ),
  'getSchemesByCategory' : IDL.Func(
      [SchemeCategory],
      [IDL.Vec(Scheme)],
      ['query'],
    ),
  'getTopUpvotedPosts' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(CommunityPost)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initialize' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markPostAsResolved' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitCommunityPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, PostCategory],
      [IDL.Nat],
      [],
    ),
  'upvotePost' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SchemeCategory = IDL.Variant({
    'finance' : IDL.Null,
    'education' : IDL.Null,
    'employment' : IDL.Null,
    'women' : IDL.Null,
    'agriculture' : IDL.Null,
    'health' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PostCategory = IDL.Variant({
    'womenEmpowerment' : IDL.Null,
    'education' : IDL.Null,
    'infrastructure' : IDL.Null,
    'agriculture' : IDL.Null,
    'digitalAccess' : IDL.Null,
    'health' : IDL.Null,
  });
  const CommunityPost = IDL.Record({
    'id' : IDL.Nat,
    'upvotes' : IDL.Nat,
    'resolved' : IDL.Bool,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'category' : PostCategory,
    'location' : IDL.Text,
  });
  const Scheme = IDL.Record({
    'id' : IDL.Nat,
    'applyLink' : IDL.Text,
    'name' : IDL.Text,
    'eligibility' : IDL.Text,
    'category' : SchemeCategory,
    'benefits' : IDL.Text,
  });
  const SuccessStory = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'sdgTags' : IDL.Vec(IDL.Text),
    'story' : IDL.Text,
    'location' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const PlatformStats = IDL.Record({
    'totalSchemes' : IDL.Nat,
    'totalUpvotes' : IDL.Nat,
    'totalPosts' : IDL.Nat,
    'totalStories' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addScheme' : IDL.Func(
        [IDL.Text, SchemeCategory, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addSuccessStory' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllCommunityPosts' : IDL.Func([], [IDL.Vec(CommunityPost)], ['query']),
    'getAllSchemes' : IDL.Func([], [IDL.Vec(Scheme)], ['query']),
    'getAllSuccessStories' : IDL.Func([], [IDL.Vec(SuccessStory)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPlatformStats' : IDL.Func([], [PlatformStats], ['query']),
    'getPostsByCategory' : IDL.Func(
        [PostCategory],
        [IDL.Vec(CommunityPost)],
        ['query'],
      ),
    'getSchemesByCategory' : IDL.Func(
        [SchemeCategory],
        [IDL.Vec(Scheme)],
        ['query'],
      ),
    'getTopUpvotedPosts' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(CommunityPost)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initialize' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markPostAsResolved' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitCommunityPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, PostCategory],
        [IDL.Nat],
        [],
      ),
    'upvotePost' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };